name: ROM Prerelease

on:
  push:
    tags:
      - 'pr*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          sudo apt-get install -y make build-essential
          git clone https://github.com/cc65/cc65.git
          cd cc65
          make -j4
          sudo make install
      - name: Build ROM
        run: |
          export PRERELEASE_VERSION=$(echo "$GITHUB_REF" | sed -e 's/^.*r\([0-9]+\)$/\1/')
          make
          mkdir artifact
          cp build/x16/*.h artifact/.
          cp build/x16/*.sym artifact/.
          cp build/x16/rom.bin artifact/.
      - name: Archive Build Result
        uses: actions/upload-artifact@v3
        with:
          name: ROM Prerelease
          path: artifact
