name: ROM Release

on:
  push:
    tags:
      - 'r*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Source Code.zip'
          exclusions: '*.git'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          sudo apt-get install -y make build-essential
          git clone https://github.com/cc65/cc65.git
          cd cc65
          make -j4
          sudo make install
      - name: Build ROM
        run: |
          make -DPRERELEASE_VERSION=42
          mkdir artifact
          cp build/x16/*.h artifact/.
          cp build/x16/*.sym artifact/.
          cp build/x16/rom.bin artifact/.
      - name: Archive Build Result
        uses: actions/upload-artifact@v3
        with:
          name: ROM Release
          path: artifact
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changelog
            - Changes are detailed in the x16-emulator releases
          draft: true
          prerelease: true
